include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
